spring:
  jackson:
    default-property-inclusion: non_empty
    time-zone: GMT+8
    date-format: yyyy-MM-dd
  datasource:
    url: jdbc:mariadb://localhost:3306/nj_aks?characterEncoding=utf-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: jiyufei1991!
mybatis:
  type-aliases-package: com.aks.management.dao
  mapper-locations: classpath:mapper/*Mapper.xml

pagehelper:
  helper-dialect: mariadb
  reasonable: true
  support-methods-arguments: true
  page-size-zero: true


springdoc:
  api-docs:
    enabled: true
    #path: /v3/api-docs
  swagger-ui:
    enabled: true
    #path: /swagger-ui.html
    url: /v3/api-docs
  packages-to-scan: com.aks.management.controller

