### addBank
POST http://localhost:8080/api/addBank
Accept: application/json
Content-Type: application/x-www-form-urlencoded

name=good1

### login-sha
POST http://localhost:8080/api/authentication/login
Accept: application/json
Content-Type: application/json

{
  "username": "test",
  "password": "AC9689E2272427085E35B9D3E3E8BED88CB3434828B43B86FC0596CAD4C6E270"
}

### login
POST http://localhost:8080/api/login
Accept: application/json
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}

###getPersonInfo

GET http://localhost:8080/api/getPersonInfo
Accept: application/json
Content-Type: application/x-www-form-urlencoded

id=2

###getPersonList

GET http://localhost:8080/api/getPersonList
Accept: application/json
Content-Type: application/x-www-form-urlencoded


###
