package com.aks.management.dao;

import com.aks.management.bean.CargoChangeRecord;
import com.aks.management.bean.CargoChangeRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CargoChangeRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo_change_record
     *
     * @mbg.generated
     */
    long countByExample(CargoChangeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo_change_record
     *
     * @mbg.generated
     */
    int deleteByExample(CargoChangeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo_change_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo_change_record
     *
     * @mbg.generated
     */
    int insert(CargoChangeRecord row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo_change_record
     *
     * @mbg.generated
     */
    int insertSelective(CargoChangeRecord row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo_change_record
     *
     * @mbg.generated
     */
    List<CargoChangeRecord> selectByExample(CargoChangeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo_change_record
     *
     * @mbg.generated
     */
    CargoChangeRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo_change_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") CargoChangeRecord row, @Param("example") CargoChangeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo_change_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") CargoChangeRecord row, @Param("example") CargoChangeRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo_change_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CargoChangeRecord row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo_change_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CargoChangeRecord row);
}