package com.aks.management.dao;

import com.aks.management.bean.CustomerContacts;
import com.aks.management.bean.CustomerContactsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomerContactsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_contacts
     *
     * @mbg.generated
     */
    long countByExample(CustomerContactsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_contacts
     *
     * @mbg.generated
     */
    int deleteByExample(CustomerContactsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_contacts
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_contacts
     *
     * @mbg.generated
     */
    int insert(CustomerContacts row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_contacts
     *
     * @mbg.generated
     */
    int insertSelective(CustomerContacts row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_contacts
     *
     * @mbg.generated
     */
    List<CustomerContacts> selectByExample(CustomerContactsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_contacts
     *
     * @mbg.generated
     */
    CustomerContacts selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_contacts
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") CustomerContacts row, @Param("example") CustomerContactsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_contacts
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") CustomerContacts row, @Param("example") CustomerContactsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_contacts
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CustomerContacts row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_contacts
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CustomerContacts row);
}