package com.aks.management.dao;

import com.aks.management.bean.InvoiceBase;
import com.aks.management.bean.InvoiceBaseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InvoiceBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice_base
     *
     * @mbg.generated
     */
    long countByExample(InvoiceBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice_base
     *
     * @mbg.generated
     */
    int deleteByExample(InvoiceBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice_base
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice_base
     *
     * @mbg.generated
     */
    int insert(InvoiceBase row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice_base
     *
     * @mbg.generated
     */
    int insertSelective(InvoiceBase row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice_base
     *
     * @mbg.generated
     */
    List<InvoiceBase> selectByExample(InvoiceBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice_base
     *
     * @mbg.generated
     */
    InvoiceBase selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice_base
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") InvoiceBase row, @Param("example") InvoiceBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice_base
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") InvoiceBase row, @Param("example") InvoiceBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice_base
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InvoiceBase row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoice_base
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InvoiceBase row);
}