package com.aks.management.dao;

import com.aks.management.bean.PayStage;
import com.aks.management.bean.PayStageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PayStageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_stage
     *
     * @mbg.generated
     */
    long countByExample(PayStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_stage
     *
     * @mbg.generated
     */
    int deleteByExample(PayStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_stage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_stage
     *
     * @mbg.generated
     */
    int insert(PayStage row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_stage
     *
     * @mbg.generated
     */
    int insertSelective(PayStage row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_stage
     *
     * @mbg.generated
     */
    List<PayStage> selectByExample(PayStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_stage
     *
     * @mbg.generated
     */
    PayStage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_stage
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") PayStage row, @Param("example") PayStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_stage
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") PayStage row, @Param("example") PayStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_stage
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PayStage row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_stage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PayStage row);
}