package com.aks.management.dao;

import com.aks.management.bean.PurchaseSale;
import com.aks.management.bean.PurchaseSaleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PurchaseSaleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_sale
     *
     * @mbg.generated
     */
    long countByExample(PurchaseSaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_sale
     *
     * @mbg.generated
     */
    int deleteByExample(PurchaseSaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_sale
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_sale
     *
     * @mbg.generated
     */
    int insert(PurchaseSale row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_sale
     *
     * @mbg.generated
     */
    int insertSelective(PurchaseSale row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_sale
     *
     * @mbg.generated
     */
    List<PurchaseSale> selectByExample(PurchaseSaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_sale
     *
     * @mbg.generated
     */
    PurchaseSale selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_sale
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") PurchaseSale row, @Param("example") PurchaseSaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_sale
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") PurchaseSale row, @Param("example") PurchaseSaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_sale
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PurchaseSale row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_sale
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PurchaseSale row);
}