package com.aks.management.dao;

import com.aks.management.bean.Purchase;
import com.aks.management.bean.PurchaseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PurchaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbg.generated
     */
    long countByExample(PurchaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbg.generated
     */
    int deleteByExample(PurchaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbg.generated
     */
    int insert(Purchase row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbg.generated
     */
    int insertSelective(Purchase row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbg.generated
     */
    List<Purchase> selectByExample(PurchaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbg.generated
     */
    Purchase selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") Purchase row, @Param("example") PurchaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") Purchase row, @Param("example") PurchaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Purchase row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Purchase row);
}