package com.aks.management.bean;

import java.time.LocalDateTime;

public class CargoChangeRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cargo_change_record.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cargo_change_record.cargo_id
     *
     * @mbg.generated
     */
    private Long cargoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cargo_change_record.purchase_id
     *
     * @mbg.generated
     */
    private Long purchaseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cargo_change_record.sale_id
     *
     * @mbg.generated
     */
    private Long saleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cargo_change_record.change_type
     *
     * @mbg.generated
     */
    private Integer changeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cargo_change_record.change_num
     *
     * @mbg.generated
     */
    private Double changeNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cargo_change_record.old_num
     *
     * @mbg.generated
     */
    private Double oldNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cargo_change_record.new_num
     *
     * @mbg.generated
     */
    private Double newNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cargo_change_record.flag
     *
     * @mbg.generated
     */
    private String flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cargo_change_record.flag2
     *
     * @mbg.generated
     */
    private String flag2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cargo_change_record.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cargo_change_record.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cargo_change_record.comments
     *
     * @mbg.generated
     */
    private String comments;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cargo_change_record.id
     *
     * @return the value of cargo_change_record.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cargo_change_record.id
     *
     * @param id the value for cargo_change_record.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cargo_change_record.cargo_id
     *
     * @return the value of cargo_change_record.cargo_id
     *
     * @mbg.generated
     */
    public Long getCargoId() {
        return cargoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cargo_change_record.cargo_id
     *
     * @param cargoId the value for cargo_change_record.cargo_id
     *
     * @mbg.generated
     */
    public void setCargoId(Long cargoId) {
        this.cargoId = cargoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cargo_change_record.purchase_id
     *
     * @return the value of cargo_change_record.purchase_id
     *
     * @mbg.generated
     */
    public Long getPurchaseId() {
        return purchaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cargo_change_record.purchase_id
     *
     * @param purchaseId the value for cargo_change_record.purchase_id
     *
     * @mbg.generated
     */
    public void setPurchaseId(Long purchaseId) {
        this.purchaseId = purchaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cargo_change_record.sale_id
     *
     * @return the value of cargo_change_record.sale_id
     *
     * @mbg.generated
     */
    public Long getSaleId() {
        return saleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cargo_change_record.sale_id
     *
     * @param saleId the value for cargo_change_record.sale_id
     *
     * @mbg.generated
     */
    public void setSaleId(Long saleId) {
        this.saleId = saleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cargo_change_record.change_type
     *
     * @return the value of cargo_change_record.change_type
     *
     * @mbg.generated
     */
    public Integer getChangeType() {
        return changeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cargo_change_record.change_type
     *
     * @param changeType the value for cargo_change_record.change_type
     *
     * @mbg.generated
     */
    public void setChangeType(Integer changeType) {
        this.changeType = changeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cargo_change_record.change_num
     *
     * @return the value of cargo_change_record.change_num
     *
     * @mbg.generated
     */
    public Double getChangeNum() {
        return changeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cargo_change_record.change_num
     *
     * @param changeNum the value for cargo_change_record.change_num
     *
     * @mbg.generated
     */
    public void setChangeNum(Double changeNum) {
        this.changeNum = changeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cargo_change_record.old_num
     *
     * @return the value of cargo_change_record.old_num
     *
     * @mbg.generated
     */
    public Double getOldNum() {
        return oldNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cargo_change_record.old_num
     *
     * @param oldNum the value for cargo_change_record.old_num
     *
     * @mbg.generated
     */
    public void setOldNum(Double oldNum) {
        this.oldNum = oldNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cargo_change_record.new_num
     *
     * @return the value of cargo_change_record.new_num
     *
     * @mbg.generated
     */
    public Double getNewNum() {
        return newNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cargo_change_record.new_num
     *
     * @param newNum the value for cargo_change_record.new_num
     *
     * @mbg.generated
     */
    public void setNewNum(Double newNum) {
        this.newNum = newNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cargo_change_record.flag
     *
     * @return the value of cargo_change_record.flag
     *
     * @mbg.generated
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cargo_change_record.flag
     *
     * @param flag the value for cargo_change_record.flag
     *
     * @mbg.generated
     */
    public void setFlag(String flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cargo_change_record.flag2
     *
     * @return the value of cargo_change_record.flag2
     *
     * @mbg.generated
     */
    public String getFlag2() {
        return flag2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cargo_change_record.flag2
     *
     * @param flag2 the value for cargo_change_record.flag2
     *
     * @mbg.generated
     */
    public void setFlag2(String flag2) {
        this.flag2 = flag2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cargo_change_record.state
     *
     * @return the value of cargo_change_record.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cargo_change_record.state
     *
     * @param state the value for cargo_change_record.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cargo_change_record.create_time
     *
     * @return the value of cargo_change_record.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cargo_change_record.create_time
     *
     * @param createTime the value for cargo_change_record.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cargo_change_record.comments
     *
     * @return the value of cargo_change_record.comments
     *
     * @mbg.generated
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cargo_change_record.comments
     *
     * @param comments the value for cargo_change_record.comments
     *
     * @mbg.generated
     */
    public void setComments(String comments) {
        this.comments = comments;
    }
}