package com.aks.management.bean;

import java.time.LocalDateTime;

public class Cargo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cargo.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cargo.cargo_name
     *
     * @mbg.generated
     */
    private String cargoName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cargo.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cargo.brand
     *
     * @mbg.generated
     */
    private String brand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cargo.cargo_type
     *
     * @mbg.generated
     */
    private String cargoType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cargo.unit
     *
     * @mbg.generated
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cargo.images
     *
     * @mbg.generated
     */
    private String images;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cargo.attachment
     *
     * @mbg.generated
     */
    private String attachment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cargo.num
     *
     * @mbg.generated
     */
    private Double num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cargo.flag
     *
     * @mbg.generated
     */
    private String flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cargo.flag2
     *
     * @mbg.generated
     */
    private String flag2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cargo.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cargo.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cargo.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cargo.comments
     *
     * @mbg.generated
     */
    private String comments;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cargo.id
     *
     * @return the value of cargo.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cargo.id
     *
     * @param id the value for cargo.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cargo.cargo_name
     *
     * @return the value of cargo.cargo_name
     *
     * @mbg.generated
     */
    public String getCargoName() {
        return cargoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cargo.cargo_name
     *
     * @param cargoName the value for cargo.cargo_name
     *
     * @mbg.generated
     */
    public void setCargoName(String cargoName) {
        this.cargoName = cargoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cargo.description
     *
     * @return the value of cargo.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cargo.description
     *
     * @param description the value for cargo.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cargo.brand
     *
     * @return the value of cargo.brand
     *
     * @mbg.generated
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cargo.brand
     *
     * @param brand the value for cargo.brand
     *
     * @mbg.generated
     */
    public void setBrand(String brand) {
        this.brand = brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cargo.cargo_type
     *
     * @return the value of cargo.cargo_type
     *
     * @mbg.generated
     */
    public String getCargoType() {
        return cargoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cargo.cargo_type
     *
     * @param cargoType the value for cargo.cargo_type
     *
     * @mbg.generated
     */
    public void setCargoType(String cargoType) {
        this.cargoType = cargoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cargo.unit
     *
     * @return the value of cargo.unit
     *
     * @mbg.generated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cargo.unit
     *
     * @param unit the value for cargo.unit
     *
     * @mbg.generated
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cargo.images
     *
     * @return the value of cargo.images
     *
     * @mbg.generated
     */
    public String getImages() {
        return images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cargo.images
     *
     * @param images the value for cargo.images
     *
     * @mbg.generated
     */
    public void setImages(String images) {
        this.images = images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cargo.attachment
     *
     * @return the value of cargo.attachment
     *
     * @mbg.generated
     */
    public String getAttachment() {
        return attachment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cargo.attachment
     *
     * @param attachment the value for cargo.attachment
     *
     * @mbg.generated
     */
    public void setAttachment(String attachment) {
        this.attachment = attachment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cargo.num
     *
     * @return the value of cargo.num
     *
     * @mbg.generated
     */
    public Double getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cargo.num
     *
     * @param num the value for cargo.num
     *
     * @mbg.generated
     */
    public void setNum(Double num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cargo.flag
     *
     * @return the value of cargo.flag
     *
     * @mbg.generated
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cargo.flag
     *
     * @param flag the value for cargo.flag
     *
     * @mbg.generated
     */
    public void setFlag(String flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cargo.flag2
     *
     * @return the value of cargo.flag2
     *
     * @mbg.generated
     */
    public String getFlag2() {
        return flag2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cargo.flag2
     *
     * @param flag2 the value for cargo.flag2
     *
     * @mbg.generated
     */
    public void setFlag2(String flag2) {
        this.flag2 = flag2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cargo.state
     *
     * @return the value of cargo.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cargo.state
     *
     * @param state the value for cargo.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cargo.create_time
     *
     * @return the value of cargo.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cargo.create_time
     *
     * @param createTime the value for cargo.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cargo.update_time
     *
     * @return the value of cargo.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cargo.update_time
     *
     * @param updateTime the value for cargo.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cargo.comments
     *
     * @return the value of cargo.comments
     *
     * @mbg.generated
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cargo.comments
     *
     * @param comments the value for cargo.comments
     *
     * @mbg.generated
     */
    public void setComments(String comments) {
        this.comments = comments;
    }
}