package com.aks.management.bean;

import java.time.LocalDateTime;

public class CustomerContacts {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_contacts.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_contacts.customer_id
     *
     * @mbg.generated
     */
    private Long customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_contacts.cc_name
     *
     * @mbg.generated
     */
    private String ccName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_contacts.department
     *
     * @mbg.generated
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_contacts.job
     *
     * @mbg.generated
     */
    private String job;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_contacts.base_location
     *
     * @mbg.generated
     */
    private String baseLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_contacts.telephone
     *
     * @mbg.generated
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_contacts.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_contacts.mail
     *
     * @mbg.generated
     */
    private String mail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_contacts.qq
     *
     * @mbg.generated
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_contacts.wechat
     *
     * @mbg.generated
     */
    private String wechat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_contacts.flag
     *
     * @mbg.generated
     */
    private String flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_contacts.flag2
     *
     * @mbg.generated
     */
    private String flag2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_contacts.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_contacts.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_contacts.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_contacts.comments
     *
     * @mbg.generated
     */
    private String comments;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_contacts.id
     *
     * @return the value of customer_contacts.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_contacts.id
     *
     * @param id the value for customer_contacts.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_contacts.customer_id
     *
     * @return the value of customer_contacts.customer_id
     *
     * @mbg.generated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_contacts.customer_id
     *
     * @param customerId the value for customer_contacts.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_contacts.cc_name
     *
     * @return the value of customer_contacts.cc_name
     *
     * @mbg.generated
     */
    public String getCcName() {
        return ccName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_contacts.cc_name
     *
     * @param ccName the value for customer_contacts.cc_name
     *
     * @mbg.generated
     */
    public void setCcName(String ccName) {
        this.ccName = ccName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_contacts.department
     *
     * @return the value of customer_contacts.department
     *
     * @mbg.generated
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_contacts.department
     *
     * @param department the value for customer_contacts.department
     *
     * @mbg.generated
     */
    public void setDepartment(String department) {
        this.department = department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_contacts.job
     *
     * @return the value of customer_contacts.job
     *
     * @mbg.generated
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_contacts.job
     *
     * @param job the value for customer_contacts.job
     *
     * @mbg.generated
     */
    public void setJob(String job) {
        this.job = job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_contacts.base_location
     *
     * @return the value of customer_contacts.base_location
     *
     * @mbg.generated
     */
    public String getBaseLocation() {
        return baseLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_contacts.base_location
     *
     * @param baseLocation the value for customer_contacts.base_location
     *
     * @mbg.generated
     */
    public void setBaseLocation(String baseLocation) {
        this.baseLocation = baseLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_contacts.telephone
     *
     * @return the value of customer_contacts.telephone
     *
     * @mbg.generated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_contacts.telephone
     *
     * @param telephone the value for customer_contacts.telephone
     *
     * @mbg.generated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_contacts.phone
     *
     * @return the value of customer_contacts.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_contacts.phone
     *
     * @param phone the value for customer_contacts.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_contacts.mail
     *
     * @return the value of customer_contacts.mail
     *
     * @mbg.generated
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_contacts.mail
     *
     * @param mail the value for customer_contacts.mail
     *
     * @mbg.generated
     */
    public void setMail(String mail) {
        this.mail = mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_contacts.qq
     *
     * @return the value of customer_contacts.qq
     *
     * @mbg.generated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_contacts.qq
     *
     * @param qq the value for customer_contacts.qq
     *
     * @mbg.generated
     */
    public void setQq(String qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_contacts.wechat
     *
     * @return the value of customer_contacts.wechat
     *
     * @mbg.generated
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_contacts.wechat
     *
     * @param wechat the value for customer_contacts.wechat
     *
     * @mbg.generated
     */
    public void setWechat(String wechat) {
        this.wechat = wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_contacts.flag
     *
     * @return the value of customer_contacts.flag
     *
     * @mbg.generated
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_contacts.flag
     *
     * @param flag the value for customer_contacts.flag
     *
     * @mbg.generated
     */
    public void setFlag(String flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_contacts.flag2
     *
     * @return the value of customer_contacts.flag2
     *
     * @mbg.generated
     */
    public String getFlag2() {
        return flag2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_contacts.flag2
     *
     * @param flag2 the value for customer_contacts.flag2
     *
     * @mbg.generated
     */
    public void setFlag2(String flag2) {
        this.flag2 = flag2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_contacts.state
     *
     * @return the value of customer_contacts.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_contacts.state
     *
     * @param state the value for customer_contacts.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_contacts.create_time
     *
     * @return the value of customer_contacts.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_contacts.create_time
     *
     * @param createTime the value for customer_contacts.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_contacts.update_time
     *
     * @return the value of customer_contacts.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_contacts.update_time
     *
     * @param updateTime the value for customer_contacts.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_contacts.comments
     *
     * @return the value of customer_contacts.comments
     *
     * @mbg.generated
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_contacts.comments
     *
     * @param comments the value for customer_contacts.comments
     *
     * @mbg.generated
     */
    public void setComments(String comments) {
        this.comments = comments;
    }
}