package com.aks.management.bean;

import java.time.LocalDateTime;

public class OperatorLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator_log.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator_log.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator_log.operator_module
     *
     * @mbg.generated
     */
    private String operatorModule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator_log.operator_action
     *
     * @mbg.generated
     */
    private String operatorAction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator_log.operator_object
     *
     * @mbg.generated
     */
    private String operatorObject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator_log.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator_log.result
     *
     * @mbg.generated
     */
    private String result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator_log.reason
     *
     * @mbg.generated
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator_log.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator_log.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operator_log.id
     *
     * @return the value of operator_log.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operator_log.id
     *
     * @param id the value for operator_log.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operator_log.user_id
     *
     * @return the value of operator_log.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operator_log.user_id
     *
     * @param userId the value for operator_log.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operator_log.operator_module
     *
     * @return the value of operator_log.operator_module
     *
     * @mbg.generated
     */
    public String getOperatorModule() {
        return operatorModule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operator_log.operator_module
     *
     * @param operatorModule the value for operator_log.operator_module
     *
     * @mbg.generated
     */
    public void setOperatorModule(String operatorModule) {
        this.operatorModule = operatorModule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operator_log.operator_action
     *
     * @return the value of operator_log.operator_action
     *
     * @mbg.generated
     */
    public String getOperatorAction() {
        return operatorAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operator_log.operator_action
     *
     * @param operatorAction the value for operator_log.operator_action
     *
     * @mbg.generated
     */
    public void setOperatorAction(String operatorAction) {
        this.operatorAction = operatorAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operator_log.operator_object
     *
     * @return the value of operator_log.operator_object
     *
     * @mbg.generated
     */
    public String getOperatorObject() {
        return operatorObject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operator_log.operator_object
     *
     * @param operatorObject the value for operator_log.operator_object
     *
     * @mbg.generated
     */
    public void setOperatorObject(String operatorObject) {
        this.operatorObject = operatorObject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operator_log.content
     *
     * @return the value of operator_log.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operator_log.content
     *
     * @param content the value for operator_log.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operator_log.result
     *
     * @return the value of operator_log.result
     *
     * @mbg.generated
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operator_log.result
     *
     * @param result the value for operator_log.result
     *
     * @mbg.generated
     */
    public void setResult(String result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operator_log.reason
     *
     * @return the value of operator_log.reason
     *
     * @mbg.generated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operator_log.reason
     *
     * @param reason the value for operator_log.reason
     *
     * @mbg.generated
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operator_log.create_time
     *
     * @return the value of operator_log.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operator_log.create_time
     *
     * @param createTime the value for operator_log.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operator_log.state
     *
     * @return the value of operator_log.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operator_log.state
     *
     * @param state the value for operator_log.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }
}