package com.aks.management.bean;

import java.time.LocalDateTime;

public class PurchaseCargo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_cargo.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_cargo.purchase_id
     *
     * @mbg.generated
     */
    private Long purchaseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_cargo.cargo_id
     *
     * @mbg.generated
     */
    private Long cargoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_cargo.num
     *
     * @mbg.generated
     */
    private Double num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_cargo.used_num
     *
     * @mbg.generated
     */
    private Integer usedNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_cargo.available_num
     *
     * @mbg.generated
     */
    private Integer availableNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_cargo.price
     *
     * @mbg.generated
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_cargo.total_price
     *
     * @mbg.generated
     */
    private Double totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_cargo.balance_cost
     *
     * @mbg.generated
     */
    private Double balanceCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_cargo.balance_cost_sale_cargo_id
     *
     * @mbg.generated
     */
    private Double balanceCostSaleCargoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_cargo.express_company
     *
     * @mbg.generated
     */
    private String expressCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_cargo.express_id
     *
     * @mbg.generated
     */
    private String expressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_cargo.deliver_address
     *
     * @mbg.generated
     */
    private String deliverAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_cargo.flag
     *
     * @mbg.generated
     */
    private String flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_cargo.flag2
     *
     * @mbg.generated
     */
    private String flag2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_cargo.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_cargo.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_cargo.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_cargo.comments
     *
     * @mbg.generated
     */
    private String comments;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_cargo.id
     *
     * @return the value of purchase_cargo.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_cargo.id
     *
     * @param id the value for purchase_cargo.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_cargo.purchase_id
     *
     * @return the value of purchase_cargo.purchase_id
     *
     * @mbg.generated
     */
    public Long getPurchaseId() {
        return purchaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_cargo.purchase_id
     *
     * @param purchaseId the value for purchase_cargo.purchase_id
     *
     * @mbg.generated
     */
    public void setPurchaseId(Long purchaseId) {
        this.purchaseId = purchaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_cargo.cargo_id
     *
     * @return the value of purchase_cargo.cargo_id
     *
     * @mbg.generated
     */
    public Long getCargoId() {
        return cargoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_cargo.cargo_id
     *
     * @param cargoId the value for purchase_cargo.cargo_id
     *
     * @mbg.generated
     */
    public void setCargoId(Long cargoId) {
        this.cargoId = cargoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_cargo.num
     *
     * @return the value of purchase_cargo.num
     *
     * @mbg.generated
     */
    public Double getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_cargo.num
     *
     * @param num the value for purchase_cargo.num
     *
     * @mbg.generated
     */
    public void setNum(Double num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_cargo.used_num
     *
     * @return the value of purchase_cargo.used_num
     *
     * @mbg.generated
     */
    public Integer getUsedNum() {
        return usedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_cargo.used_num
     *
     * @param usedNum the value for purchase_cargo.used_num
     *
     * @mbg.generated
     */
    public void setUsedNum(Integer usedNum) {
        this.usedNum = usedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_cargo.available_num
     *
     * @return the value of purchase_cargo.available_num
     *
     * @mbg.generated
     */
    public Integer getAvailableNum() {
        return availableNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_cargo.available_num
     *
     * @param availableNum the value for purchase_cargo.available_num
     *
     * @mbg.generated
     */
    public void setAvailableNum(Integer availableNum) {
        this.availableNum = availableNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_cargo.price
     *
     * @return the value of purchase_cargo.price
     *
     * @mbg.generated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_cargo.price
     *
     * @param price the value for purchase_cargo.price
     *
     * @mbg.generated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_cargo.total_price
     *
     * @return the value of purchase_cargo.total_price
     *
     * @mbg.generated
     */
    public Double getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_cargo.total_price
     *
     * @param totalPrice the value for purchase_cargo.total_price
     *
     * @mbg.generated
     */
    public void setTotalPrice(Double totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_cargo.balance_cost
     *
     * @return the value of purchase_cargo.balance_cost
     *
     * @mbg.generated
     */
    public Double getBalanceCost() {
        return balanceCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_cargo.balance_cost
     *
     * @param balanceCost the value for purchase_cargo.balance_cost
     *
     * @mbg.generated
     */
    public void setBalanceCost(Double balanceCost) {
        this.balanceCost = balanceCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_cargo.balance_cost_sale_cargo_id
     *
     * @return the value of purchase_cargo.balance_cost_sale_cargo_id
     *
     * @mbg.generated
     */
    public Double getBalanceCostSaleCargoId() {
        return balanceCostSaleCargoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_cargo.balance_cost_sale_cargo_id
     *
     * @param balanceCostSaleCargoId the value for purchase_cargo.balance_cost_sale_cargo_id
     *
     * @mbg.generated
     */
    public void setBalanceCostSaleCargoId(Double balanceCostSaleCargoId) {
        this.balanceCostSaleCargoId = balanceCostSaleCargoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_cargo.express_company
     *
     * @return the value of purchase_cargo.express_company
     *
     * @mbg.generated
     */
    public String getExpressCompany() {
        return expressCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_cargo.express_company
     *
     * @param expressCompany the value for purchase_cargo.express_company
     *
     * @mbg.generated
     */
    public void setExpressCompany(String expressCompany) {
        this.expressCompany = expressCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_cargo.express_id
     *
     * @return the value of purchase_cargo.express_id
     *
     * @mbg.generated
     */
    public String getExpressId() {
        return expressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_cargo.express_id
     *
     * @param expressId the value for purchase_cargo.express_id
     *
     * @mbg.generated
     */
    public void setExpressId(String expressId) {
        this.expressId = expressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_cargo.deliver_address
     *
     * @return the value of purchase_cargo.deliver_address
     *
     * @mbg.generated
     */
    public String getDeliverAddress() {
        return deliverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_cargo.deliver_address
     *
     * @param deliverAddress the value for purchase_cargo.deliver_address
     *
     * @mbg.generated
     */
    public void setDeliverAddress(String deliverAddress) {
        this.deliverAddress = deliverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_cargo.flag
     *
     * @return the value of purchase_cargo.flag
     *
     * @mbg.generated
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_cargo.flag
     *
     * @param flag the value for purchase_cargo.flag
     *
     * @mbg.generated
     */
    public void setFlag(String flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_cargo.flag2
     *
     * @return the value of purchase_cargo.flag2
     *
     * @mbg.generated
     */
    public String getFlag2() {
        return flag2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_cargo.flag2
     *
     * @param flag2 the value for purchase_cargo.flag2
     *
     * @mbg.generated
     */
    public void setFlag2(String flag2) {
        this.flag2 = flag2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_cargo.state
     *
     * @return the value of purchase_cargo.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_cargo.state
     *
     * @param state the value for purchase_cargo.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_cargo.create_time
     *
     * @return the value of purchase_cargo.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_cargo.create_time
     *
     * @param createTime the value for purchase_cargo.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_cargo.update_time
     *
     * @return the value of purchase_cargo.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_cargo.update_time
     *
     * @param updateTime the value for purchase_cargo.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_cargo.comments
     *
     * @return the value of purchase_cargo.comments
     *
     * @mbg.generated
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_cargo.comments
     *
     * @param comments the value for purchase_cargo.comments
     *
     * @mbg.generated
     */
    public void setComments(String comments) {
        this.comments = comments;
    }
}