package com.aks.management.bean;

import java.time.LocalDateTime;

public class PurchaseSale {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_sale.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_sale.purchase_id
     *
     * @mbg.generated
     */
    private Long purchaseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_sale.sale_id
     *
     * @mbg.generated
     */
    private Long saleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_sale.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_sale.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_sale.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_sale.comments
     *
     * @mbg.generated
     */
    private String comments;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_sale.id
     *
     * @return the value of purchase_sale.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_sale.id
     *
     * @param id the value for purchase_sale.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_sale.purchase_id
     *
     * @return the value of purchase_sale.purchase_id
     *
     * @mbg.generated
     */
    public Long getPurchaseId() {
        return purchaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_sale.purchase_id
     *
     * @param purchaseId the value for purchase_sale.purchase_id
     *
     * @mbg.generated
     */
    public void setPurchaseId(Long purchaseId) {
        this.purchaseId = purchaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_sale.sale_id
     *
     * @return the value of purchase_sale.sale_id
     *
     * @mbg.generated
     */
    public Long getSaleId() {
        return saleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_sale.sale_id
     *
     * @param saleId the value for purchase_sale.sale_id
     *
     * @mbg.generated
     */
    public void setSaleId(Long saleId) {
        this.saleId = saleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_sale.state
     *
     * @return the value of purchase_sale.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_sale.state
     *
     * @param state the value for purchase_sale.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_sale.create_time
     *
     * @return the value of purchase_sale.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_sale.create_time
     *
     * @param createTime the value for purchase_sale.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_sale.update_time
     *
     * @return the value of purchase_sale.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_sale.update_time
     *
     * @param updateTime the value for purchase_sale.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_sale.comments
     *
     * @return the value of purchase_sale.comments
     *
     * @mbg.generated
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_sale.comments
     *
     * @param comments the value for purchase_sale.comments
     *
     * @mbg.generated
     */
    public void setComments(String comments) {
        this.comments = comments;
    }
}