package com.aks.management.bean;

import java.time.LocalDate;
import java.time.LocalDateTime;

public class SaleCargo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_cargo.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_cargo.sale_id
     *
     * @mbg.generated
     */
    private Long saleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_cargo.cargo_id
     *
     * @mbg.generated
     */
    private Long cargoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_cargo.num
     *
     * @mbg.generated
     */
    private Double num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_cargo.price
     *
     * @mbg.generated
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_cargo.total_price
     *
     * @mbg.generated
     */
    private Double totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_cargo.balance_cost
     *
     * @mbg.generated
     */
    private Double balanceCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_cargo.contract_deliver_date
     *
     * @mbg.generated
     */
    private LocalDate contractDeliverDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_cargo.expect_deliver_date
     *
     * @mbg.generated
     */
    private LocalDate expectDeliverDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_cargo.real_deliver_date
     *
     * @mbg.generated
     */
    private LocalDate realDeliverDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_cargo.deliver_address
     *
     * @mbg.generated
     */
    private String deliverAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_cargo.express_company
     *
     * @mbg.generated
     */
    private String expressCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_cargo.express_id
     *
     * @mbg.generated
     */
    private String expressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_cargo.flag
     *
     * @mbg.generated
     */
    private String flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_cargo.flag2
     *
     * @mbg.generated
     */
    private String flag2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_cargo.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_cargo.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_cargo.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_cargo.comments
     *
     * @mbg.generated
     */
    private String comments;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_cargo.id
     *
     * @return the value of sale_cargo.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_cargo.id
     *
     * @param id the value for sale_cargo.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_cargo.sale_id
     *
     * @return the value of sale_cargo.sale_id
     *
     * @mbg.generated
     */
    public Long getSaleId() {
        return saleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_cargo.sale_id
     *
     * @param saleId the value for sale_cargo.sale_id
     *
     * @mbg.generated
     */
    public void setSaleId(Long saleId) {
        this.saleId = saleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_cargo.cargo_id
     *
     * @return the value of sale_cargo.cargo_id
     *
     * @mbg.generated
     */
    public Long getCargoId() {
        return cargoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_cargo.cargo_id
     *
     * @param cargoId the value for sale_cargo.cargo_id
     *
     * @mbg.generated
     */
    public void setCargoId(Long cargoId) {
        this.cargoId = cargoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_cargo.num
     *
     * @return the value of sale_cargo.num
     *
     * @mbg.generated
     */
    public Double getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_cargo.num
     *
     * @param num the value for sale_cargo.num
     *
     * @mbg.generated
     */
    public void setNum(Double num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_cargo.price
     *
     * @return the value of sale_cargo.price
     *
     * @mbg.generated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_cargo.price
     *
     * @param price the value for sale_cargo.price
     *
     * @mbg.generated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_cargo.total_price
     *
     * @return the value of sale_cargo.total_price
     *
     * @mbg.generated
     */
    public Double getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_cargo.total_price
     *
     * @param totalPrice the value for sale_cargo.total_price
     *
     * @mbg.generated
     */
    public void setTotalPrice(Double totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_cargo.balance_cost
     *
     * @return the value of sale_cargo.balance_cost
     *
     * @mbg.generated
     */
    public Double getBalanceCost() {
        return balanceCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_cargo.balance_cost
     *
     * @param balanceCost the value for sale_cargo.balance_cost
     *
     * @mbg.generated
     */
    public void setBalanceCost(Double balanceCost) {
        this.balanceCost = balanceCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_cargo.contract_deliver_date
     *
     * @return the value of sale_cargo.contract_deliver_date
     *
     * @mbg.generated
     */
    public LocalDate getContractDeliverDate() {
        return contractDeliverDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_cargo.contract_deliver_date
     *
     * @param contractDeliverDate the value for sale_cargo.contract_deliver_date
     *
     * @mbg.generated
     */
    public void setContractDeliverDate(LocalDate contractDeliverDate) {
        this.contractDeliverDate = contractDeliverDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_cargo.expect_deliver_date
     *
     * @return the value of sale_cargo.expect_deliver_date
     *
     * @mbg.generated
     */
    public LocalDate getExpectDeliverDate() {
        return expectDeliverDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_cargo.expect_deliver_date
     *
     * @param expectDeliverDate the value for sale_cargo.expect_deliver_date
     *
     * @mbg.generated
     */
    public void setExpectDeliverDate(LocalDate expectDeliverDate) {
        this.expectDeliverDate = expectDeliverDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_cargo.real_deliver_date
     *
     * @return the value of sale_cargo.real_deliver_date
     *
     * @mbg.generated
     */
    public LocalDate getRealDeliverDate() {
        return realDeliverDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_cargo.real_deliver_date
     *
     * @param realDeliverDate the value for sale_cargo.real_deliver_date
     *
     * @mbg.generated
     */
    public void setRealDeliverDate(LocalDate realDeliverDate) {
        this.realDeliverDate = realDeliverDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_cargo.deliver_address
     *
     * @return the value of sale_cargo.deliver_address
     *
     * @mbg.generated
     */
    public String getDeliverAddress() {
        return deliverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_cargo.deliver_address
     *
     * @param deliverAddress the value for sale_cargo.deliver_address
     *
     * @mbg.generated
     */
    public void setDeliverAddress(String deliverAddress) {
        this.deliverAddress = deliverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_cargo.express_company
     *
     * @return the value of sale_cargo.express_company
     *
     * @mbg.generated
     */
    public String getExpressCompany() {
        return expressCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_cargo.express_company
     *
     * @param expressCompany the value for sale_cargo.express_company
     *
     * @mbg.generated
     */
    public void setExpressCompany(String expressCompany) {
        this.expressCompany = expressCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_cargo.express_id
     *
     * @return the value of sale_cargo.express_id
     *
     * @mbg.generated
     */
    public String getExpressId() {
        return expressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_cargo.express_id
     *
     * @param expressId the value for sale_cargo.express_id
     *
     * @mbg.generated
     */
    public void setExpressId(String expressId) {
        this.expressId = expressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_cargo.flag
     *
     * @return the value of sale_cargo.flag
     *
     * @mbg.generated
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_cargo.flag
     *
     * @param flag the value for sale_cargo.flag
     *
     * @mbg.generated
     */
    public void setFlag(String flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_cargo.flag2
     *
     * @return the value of sale_cargo.flag2
     *
     * @mbg.generated
     */
    public String getFlag2() {
        return flag2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_cargo.flag2
     *
     * @param flag2 the value for sale_cargo.flag2
     *
     * @mbg.generated
     */
    public void setFlag2(String flag2) {
        this.flag2 = flag2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_cargo.state
     *
     * @return the value of sale_cargo.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_cargo.state
     *
     * @param state the value for sale_cargo.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_cargo.create_time
     *
     * @return the value of sale_cargo.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_cargo.create_time
     *
     * @param createTime the value for sale_cargo.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_cargo.update_time
     *
     * @return the value of sale_cargo.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_cargo.update_time
     *
     * @param updateTime the value for sale_cargo.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_cargo.comments
     *
     * @return the value of sale_cargo.comments
     *
     * @mbg.generated
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_cargo.comments
     *
     * @param comments the value for sale_cargo.comments
     *
     * @mbg.generated
     */
    public void setComments(String comments) {
        this.comments = comments;
    }
}