package com.aks.management.bean;

import java.time.LocalDateTime;

public class SupplierContacts {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_contacts.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_contacts.supplier_id
     *
     * @mbg.generated
     */
    private Long supplierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_contacts.sc_name
     *
     * @mbg.generated
     */
    private String scName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_contacts.department
     *
     * @mbg.generated
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_contacts.job
     *
     * @mbg.generated
     */
    private String job;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_contacts.telephone
     *
     * @mbg.generated
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_contacts.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_contacts.mail
     *
     * @mbg.generated
     */
    private String mail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_contacts.base_location
     *
     * @mbg.generated
     */
    private String baseLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_contacts.qq
     *
     * @mbg.generated
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_contacts.wechat
     *
     * @mbg.generated
     */
    private String wechat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_contacts.flag
     *
     * @mbg.generated
     */
    private String flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_contacts.flag2
     *
     * @mbg.generated
     */
    private String flag2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_contacts.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_contacts.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_contacts.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_contacts.comments
     *
     * @mbg.generated
     */
    private String comments;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_contacts.id
     *
     * @return the value of supplier_contacts.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_contacts.id
     *
     * @param id the value for supplier_contacts.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_contacts.supplier_id
     *
     * @return the value of supplier_contacts.supplier_id
     *
     * @mbg.generated
     */
    public Long getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_contacts.supplier_id
     *
     * @param supplierId the value for supplier_contacts.supplier_id
     *
     * @mbg.generated
     */
    public void setSupplierId(Long supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_contacts.sc_name
     *
     * @return the value of supplier_contacts.sc_name
     *
     * @mbg.generated
     */
    public String getScName() {
        return scName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_contacts.sc_name
     *
     * @param scName the value for supplier_contacts.sc_name
     *
     * @mbg.generated
     */
    public void setScName(String scName) {
        this.scName = scName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_contacts.department
     *
     * @return the value of supplier_contacts.department
     *
     * @mbg.generated
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_contacts.department
     *
     * @param department the value for supplier_contacts.department
     *
     * @mbg.generated
     */
    public void setDepartment(String department) {
        this.department = department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_contacts.job
     *
     * @return the value of supplier_contacts.job
     *
     * @mbg.generated
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_contacts.job
     *
     * @param job the value for supplier_contacts.job
     *
     * @mbg.generated
     */
    public void setJob(String job) {
        this.job = job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_contacts.telephone
     *
     * @return the value of supplier_contacts.telephone
     *
     * @mbg.generated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_contacts.telephone
     *
     * @param telephone the value for supplier_contacts.telephone
     *
     * @mbg.generated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_contacts.phone
     *
     * @return the value of supplier_contacts.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_contacts.phone
     *
     * @param phone the value for supplier_contacts.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_contacts.mail
     *
     * @return the value of supplier_contacts.mail
     *
     * @mbg.generated
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_contacts.mail
     *
     * @param mail the value for supplier_contacts.mail
     *
     * @mbg.generated
     */
    public void setMail(String mail) {
        this.mail = mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_contacts.base_location
     *
     * @return the value of supplier_contacts.base_location
     *
     * @mbg.generated
     */
    public String getBaseLocation() {
        return baseLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_contacts.base_location
     *
     * @param baseLocation the value for supplier_contacts.base_location
     *
     * @mbg.generated
     */
    public void setBaseLocation(String baseLocation) {
        this.baseLocation = baseLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_contacts.qq
     *
     * @return the value of supplier_contacts.qq
     *
     * @mbg.generated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_contacts.qq
     *
     * @param qq the value for supplier_contacts.qq
     *
     * @mbg.generated
     */
    public void setQq(String qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_contacts.wechat
     *
     * @return the value of supplier_contacts.wechat
     *
     * @mbg.generated
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_contacts.wechat
     *
     * @param wechat the value for supplier_contacts.wechat
     *
     * @mbg.generated
     */
    public void setWechat(String wechat) {
        this.wechat = wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_contacts.flag
     *
     * @return the value of supplier_contacts.flag
     *
     * @mbg.generated
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_contacts.flag
     *
     * @param flag the value for supplier_contacts.flag
     *
     * @mbg.generated
     */
    public void setFlag(String flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_contacts.flag2
     *
     * @return the value of supplier_contacts.flag2
     *
     * @mbg.generated
     */
    public String getFlag2() {
        return flag2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_contacts.flag2
     *
     * @param flag2 the value for supplier_contacts.flag2
     *
     * @mbg.generated
     */
    public void setFlag2(String flag2) {
        this.flag2 = flag2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_contacts.state
     *
     * @return the value of supplier_contacts.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_contacts.state
     *
     * @param state the value for supplier_contacts.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_contacts.create_time
     *
     * @return the value of supplier_contacts.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_contacts.create_time
     *
     * @param createTime the value for supplier_contacts.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_contacts.update_time
     *
     * @return the value of supplier_contacts.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_contacts.update_time
     *
     * @param updateTime the value for supplier_contacts.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_contacts.comments
     *
     * @return the value of supplier_contacts.comments
     *
     * @mbg.generated
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_contacts.comments
     *
     * @param comments the value for supplier_contacts.comments
     *
     * @mbg.generated
     */
    public void setComments(String comments) {
        this.comments = comments;
    }
}